<script setup>
import { ref, computed } from 'vue';
import { useLang } from '../useLang.js';

const props = defineProps({
  visible: { type: Boolean, default: false },
  pago: { type: Object, default: null },
  locale: { type: String, default: 'es-MX' }
});

const emit = defineEmits(['close', 'notify']);

const reciboRef = ref(null);
const modalContentRef = ref(null);
const generando = ref(false);

const { lang } = useLang();

const traducciones = {
  es: {
    modalTitle: 'RECIBO DE PAGO',
    modalSubtitle: 'Comprobante de transacción',
    receiptPreview: 'VISTA PREVIA',
    subTitle: 'COMPROBANTE DE PAGO',
    date: 'Fecha',
    time: 'Hora',
    operationNum: 'FOLIO DE OPERACIÓN',
    client: 'CLIENTE',
    registeredBy: 'REGISTRADO POR',
    mainCashier: 'CAJA PRINCIPAL',
    paymentMethod: 'MÉTODO DE PAGO',
    status: 'ESTADO',
    paid: 'PAGO CONFIRMADO',
    conceptPlan: 'CONCEPTO / PLAN',
    amount: 'IMPORTE',
    monthly: 'Mensualidad',
    monthlySurcharge: 'Mensualidad + Recargo',
    membership: 'Membresía',
    subtotal: 'Subtotal',
    vat: 'IVA',
    totalAmount: 'TOTAL PAGADO',
    authCode: 'CÓDIGO DE VERIFICACIÓN',
    authorized: 'TRANSACCIÓN AUTORIZADA',
    footer1: 'Conserve este comprobante para cualquier aclaración.',
    footer2: 'Gracias por su preferencia.',
    generatedBy: 'Generado electrónicamente por Elite Gym',
    genPng: 'Generando recibo PNG...',
    genPdf: 'Generando recibo PDF...',
    successPng: 'Recibo descargado con éxito',
    successPdf: 'Recibo PDF descargado con éxito',
    errorPng: 'Error al generar la imagen PNG',
    errorPdf: 'Error al generar el PDF. Verifica que jspdf esté instalado.',
    btnPng: 'Descargar PNG',
    btnPdf: 'Descargar PDF',
    btnClose: 'Cerrar',
    generating: 'Generando…',
    downloadAs: 'DESCARGAR COMPROBANTE',
    paymentInformation: 'INFORMACIÓN DEL PAGO',
    paymentDetail: 'DETALLE DE LA TRANSACCIÓN'
  },

  en: {
    modalTitle: 'PAYMENT RECEIPT',
    modalSubtitle: 'Transaction receipt',
    receiptPreview: 'PREVIEW',
    subTitle: 'PAYMENT RECEIPT',
    date: 'Date',
    time: 'Time',
    operationNum: 'OPERATION REFERENCE',
    client: 'CLIENT',
    registeredBy: 'REGISTERED BY',
    mainCashier: 'MAIN CASHIER',
    paymentMethod: 'PAYMENT METHOD',
    status: 'STATUS',
    paid: 'PAYMENT CONFIRMED',
    conceptPlan: 'CONCEPT / PLAN',
    amount: 'AMOUNT',
    monthly: 'Monthly',
    monthlySurcharge: 'Monthly + Surcharge',
    membership: 'Membership',
    subtotal: 'Subtotal',
    vat: 'VAT',
    totalAmount: 'TOTAL PAID',
    authCode: 'VERIFICATION CODE',
    authorized: 'AUTHORIZED TRANSACTION',
    footer1: 'Keep this receipt for any inquiries.',
    footer2: 'Thank you for your preference.',
    generatedBy: 'Electronically generated by Elite Gym',
    genPng: 'Generating PNG receipt...',
    genPdf: 'Generating PDF receipt...',
    successPng: 'Receipt downloaded successfully',
    successPdf: 'PDF receipt downloaded successfully',
    errorPng: 'Error generating PNG image',
    errorPdf: 'Error generating PDF. Verify jspdf is installed.',
    btnPng: 'Download PNG',
    btnPdf: 'Download PDF',
    btnClose: 'Close',
    generating: 'Generating…',
    downloadAs: 'DOWNLOAD RECEIPT',
    paymentInformation: 'PAYMENT INFORMATION',
    paymentDetail: 'TRANSACTION DETAILS'
  }
};

const t = computed(() => traducciones[lang.value] || traducciones.es);

const formatFecha = (iso) => {
  if (!iso) return '';

  return new Date(`${iso}T00:00:00`).toLocaleDateString(
    props.locale,
    {
      day: '2-digit',
      month: '2-digit',
      year: 'numeric'
    }
  );
};

const formatHora = () => {
  const now = new Date();

  return now.toLocaleTimeString(props.locale, {
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    hour12: false
  });
};

const montoFormateado = computed(() => {
  const val = Number(props.pago?.monto) || 0;

  return new Intl.NumberFormat(
    props.locale || 'es-MX',
    {
      minimumFractionDigits: 2,
      maximumFractionDigits: 2
    }
  ).format(val);
});

const conceptoTexto = computed(() => {
  const c = props.pago?.concepto;

  if (c === 'monthly') return t.value.monthly;
  if (c === 'monthlySurcharge') {
    return t.value.monthlySurcharge;
  }

  return t.value.membership;
});

const metodoTexto = computed(() => {
  const metodo = props.pago?.metodo;

  if (!metodo) return '—';

  if (lang.value === 'en') {
    const metodos = {
      Efectivo: 'Cash',
      Transferencia: 'Bank transfer',
      Tarjeta: 'Card'
    };

    return metodos[metodo] || metodo;
  }

  return metodo;
});

const folioCorto = computed(() => {
  return props.pago?.folio || '00000000';
});

const cerrar = () => {
  if (generando.value) return;

  emit('close');
};

/* =========================================================
   PREPARAR TICKET PARA CAPTURA
========================================================= */

const liberarRecorteParaCaptura = async () => {
  const el = reciboRef.value;
  const contenedor = modalContentRef.value;

  if (!el) return () => {};

  const original = {
    elOverflow: el.style.overflow,
    elMaxHeight: el.style.maxHeight,
    elHeight: el.style.height,
    contOverflow: contenedor?.style.overflow,
    contMaxHeight: contenedor?.style.maxHeight
  };

  el.style.overflow = 'visible';
  el.style.maxHeight = 'none';
  el.style.height = 'auto';

  if (contenedor) {
    contenedor.style.overflow = 'visible';
    contenedor.style.maxHeight = 'none';
  }

  await new Promise((resolve) =>
    requestAnimationFrame(() =>
      requestAnimationFrame(resolve)
    )
  );

  await new Promise((resolve) =>
    setTimeout(resolve, 50)
  );

  return () => {
    el.style.overflow = original.elOverflow;
    el.style.maxHeight = original.elMaxHeight;
    el.style.height = original.elHeight;

    if (contenedor) {
      contenedor.style.overflow =
        original.contOverflow;

      contenedor.style.maxHeight =
        original.contMaxHeight;
    }
  };
};

const capturarTicketCompleto = async () => {
  const html2canvas =
    (await import('html2canvas')).default;

  const el = reciboRef.value;

  if (!el) {
    throw new Error('Receipt element not found');
  }

  const restaurar =
    await liberarRecorteParaCaptura();

  try {
    const canvas = await html2canvas(el, {
      scale: 2.5,
      backgroundColor: '#ffffff',
      useCORS: true,
      logging: false
    });

    return canvas;
  } finally {
    restaurar();
  }
};

/* =========================================================
   PNG
========================================================= */

const descargarPng = async () => {
  if (!reciboRef.value || generando.value) return;

  generando.value = true;

  emit('notify', {
    message: t.value.genPng,
    type: 'info'
  });

  try {
    const canvas =
      await capturarTicketCompleto();

    const image =
      canvas.toDataURL('image/png');

    const link =
      document.createElement('a');

    link.href = image;

    link.download =
      `Ticket_${props.pago?.folio || 'pago'}.png`;

    document.body.appendChild(link);

    link.click();
    link.remove();

    emit('notify', {
      message: t.value.successPng,
      type: 'success'
    });
  } catch (error) {
    console.error(
      'Error al generar PNG:',
      error
    );

    emit('notify', {
      message: t.value.errorPng,
      type: 'error'
    });
  } finally {
    generando.value = false;
  }
};

/* =========================================================
   PDF
========================================================= */

const descargarPdf = async () => {
  if (!reciboRef.value || generando.value) return;

  generando.value = true;

  emit('notify', {
    message: t.value.genPdf,
    type: 'info'
  });

  try {
    const canvas =
      await capturarTicketCompleto();

    const { jsPDF } =
      await import('jspdf');

    const imgData =
      canvas.toDataURL('image/png');

    const anchoMm = 86;

    const altoMm =
      (canvas.height * anchoMm) /
      canvas.width;

    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: [anchoMm, altoMm]
    });

    pdf.addImage(
      imgData,
      'PNG',
      0,
      0,
      anchoMm,
      altoMm
    );

    pdf.save(
      `Ticket_${props.pago?.folio || 'pago'}.pdf`
    );

    emit('notify', {
      message: t.value.successPdf,
      type: 'success'
    });
  } catch (error) {
    console.error(
      'Error al generar PDF:',
      error
    );

    emit('notify', {
      message: t.value.errorPdf,
      type: 'error'
    });
  } finally {
    generando.value = false;
  }
};
</script>

<template>
  <div
    v-if="visible"
    class="modal-overlay"
    @click.self="cerrar"
  >
    <div
      ref="modalContentRef"
      class="modal-shell"
    >
      <!-- ================================================
           CABECERA DEL MODAL
      ================================================= -->

      <header class="modal-header">
        <div class="header-left">
          <div class="header-icon">
            <svg
              viewBox="0 0 24 24"
              width="19"
              height="19"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
            >
              <path
                d="M6 2h12a2 2 0 0 1 2 2v18l-4-2-4 2-4-2-4 2V4a2 2 0 0 1 2-2Z"
              />
              <path d="M8 7h8" />
              <path d="M8 11h8" />
            </svg>
          </div>

          <div>
            <span class="modal-kicker">
              {{ t.receiptPreview }}
            </span>

            <h3>{{ t.modalTitle }}</h3>

            <p>{{ t.modalSubtitle }}</p>
          </div>
        </div>

        <button
          type="button"
          class="close-button"
          :disabled="generando"
          aria-label="close"
          @click="cerrar"
        >
          <svg
            viewBox="0 0 24 24"
            width="18"
            height="18"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
          >
            <path d="M18 6L6 18M6 6l12 12" />
          </svg>
        </button>
      </header>

      <!-- ================================================
           VISTA PREVIA
      ================================================= -->

      <div class="receipt-viewport">
        <div
          ref="reciboRef"
          class="receipt"
        >
          <!-- HEADER DEL RECIBO -->

          <header class="receipt-header">
            <div class="receipt-brand">
              <div class="brand-mark">
                <span>E</span>
              </div>

              <div class="brand-copy">
                <strong>ELITE GYM</strong>
                <span>FITNESS CENTER</span>
              </div>
            </div>

            <div class="receipt-type">
              <span>{{ t.subTitle }}</span>
              <strong>#{{ folioCorto }}</strong>
            </div>
          </header>

          <!-- ESTADO -->

          <div class="receipt-status">
            <div class="status-icon">
              <svg
                viewBox="0 0 24 24"
                width="20"
                height="20"
                fill="none"
                stroke="currentColor"
                stroke-width="2.5"
              >
                <path d="m5 12 4 4L19 6" />
              </svg>
            </div>

            <div class="status-copy">
              <strong>{{ t.paid }}</strong>
              <span>{{ t.authorized }}</span>
            </div>

            <div class="status-code">
              <span>{{ t.status }}</span>
              <strong>OK</strong>
            </div>
          </div>

          <!-- FECHA Y HORA -->

          <div class="receipt-meta">
            <div>
              <span>{{ t.date }}</span>

              <strong>
                {{ formatFecha(pago?.fecha) }}
              </strong>
            </div>

            <div>
              <span>{{ t.time }}</span>

              <strong>
                {{ formatHora() }}
              </strong>
            </div>

            <div>
              <span>{{ t.paymentMethod }}</span>

              <strong>
                {{ metodoTexto }}
              </strong>
            </div>
          </div>

          <!-- INFORMACIÓN -->

          <section class="receipt-section">
            <div class="section-label">
              {{ t.paymentInformation }}
            </div>

            <div class="information-list">
              <div class="information-row">
                <span>{{ t.operationNum }}</span>

                <strong class="mono">
                  {{ pago?.folio || '—' }}
                </strong>
              </div>

              <div class="information-row">
                <span>{{ t.client }}</span>

                <strong>
                  {{ pago?.cliente || '—' }}
                </strong>
              </div>

              <div class="information-row">
                <span>{{ t.registeredBy }}</span>

                <strong>
                  {{ t.mainCashier }}
                </strong>
              </div>

              <div class="information-row">
                <span>{{ t.paymentMethod }}</span>

                <strong>
                  {{ metodoTexto }}
                </strong>
              </div>
            </div>
          </section>

          <!-- DETALLE -->

          <section class="receipt-section">
            <div class="section-label">
              {{ t.paymentDetail }}
            </div>

            <div class="concept-header">
              <span>{{ t.conceptPlan }}</span>
              <span>{{ t.amount }}</span>
            </div>

            <div class="concept-row">
              <div>
                <strong>{{ conceptoTexto }}</strong>

                <span>
                  {{ pago?.plan || '—' }}
                </span>
              </div>

              <strong class="concept-amount mono">
                ${{ montoFormateado }}
              </strong>
            </div>
          </section>

          <!-- TOTAL -->

          <section class="totals-section">
            <div class="subtotal-row">
              <span>{{ t.subtotal }}</span>

              <strong class="mono">
                ${{ montoFormateado }}
              </strong>
            </div>

            <div class="subtotal-row">
              <span>{{ t.vat }} (0%)</span>

              <strong class="mono">
                $0.00
              </strong>
            </div>

            <div class="total-divider"></div>

            <div class="grand-total">
              <div>
                <span>{{ t.totalAmount }}</span>
                <small>MXN</small>
              </div>

              <strong class="mono">
                ${{ montoFormateado }}
              </strong>
            </div>
          </section>

          <!-- CÓDIGO DE VERIFICACIÓN -->

          <section class="verification">
            <div class="barcode">
              <span
                v-for="n in 36"
                :key="n"
                class="barcode-line"
                :class="{
                  wide: n % 4 === 0,
                  medium: n % 3 === 0
                }"
              ></span>
            </div>

            <strong class="verification-number">
              {{ pago?.folio || '00000000' }}
            </strong>

            <span class="verification-label">
              {{ t.authCode }}
            </span>
          </section>

          <!-- FOOTER -->

          <footer class="receipt-footer">
            <div class="footer-check">
              <svg
                viewBox="0 0 24 24"
                width="13"
                height="13"
                fill="none"
                stroke="currentColor"
                stroke-width="2.5"
              >
                <path d="m5 12 4 4L19 6" />
              </svg>

              {{ t.authorized }}
            </div>

            <p>{{ t.footer1 }}</p>
            <strong>{{ t.footer2 }}</strong>

            <div class="footer-divider"></div>

            <span>
              ELITE GYM FITNESS CENTER
            </span>

            <small>
              RFC: EGY210415XYZ
            </small>

            <small>
              {{ t.generatedBy }}
            </small>
          </footer>
        </div>
      </div>

      <!-- ================================================
           ACCIONES
      ================================================= -->

      <footer class="modal-footer">
        <div class="download-title">
          <span>{{ t.downloadAs }}</span>

          <small>
            PNG / PDF
          </small>
        </div>

        <div class="modal-actions">
          <button
            type="button"
            class="action-button png-button"
            :disabled="generando"
            @click="descargarPng"
          >
            <span class="action-icon">
              <svg
                viewBox="0 0 24 24"
                width="17"
                height="17"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
              >
                <rect
                  x="3"
                  y="3"
                  width="18"
                  height="18"
                  rx="2"
                />
                <circle
                  cx="8.5"
                  cy="8.5"
                  r="1.5"
                />
                <path d="m21 15-5-5L5 21" />
              </svg>
            </span>

            <span>
              <strong>
                {{
                  generando
                    ? t.generating
                    : t.btnPng
                }}
              </strong>

              <small>
                {{ generando ? '...' : 'Imagen' }}
              </small>
            </span>
          </button>

          <button
            type="button"
            class="action-button pdf-button"
            :disabled="generando"
            @click="descargarPdf"
          >
            <span class="action-icon">
              <svg
                viewBox="0 0 24 24"
                width="17"
                height="17"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
              >
                <path
                  d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"
                />
                <path d="M14 2v6h6" />
                <path d="M8 13h8" />
                <path d="M8 17h6" />
              </svg>
            </span>

            <span>
              <strong>
                {{
                  generando
                    ? t.generating
                    : t.btnPdf
                }}
              </strong>

              <small>
                Documento
              </small>
            </span>
          </button>

          <button
            type="button"
            class="close-footer-button"
            :disabled="generando"
            @click="cerrar"
          >
            {{ t.btnClose }}
          </button>
        </div>
      </footer>
    </div>
  </div>
</template>

<style scoped>
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=IBM+Plex+Mono:wght@500;600;700&family=Oswald:wght@500;600;700&display=swap');

* {
  box-sizing: border-box;
}

/* =========================================================
   MODAL
========================================================= */

.modal-overlay {
  --accent: var(--color-highlight, #3b82f6);
  --card: var(--bg-cards, #111317);
  --text: var(--color-texto-general, #f5f7fa);
  --title: var(--color-titulos, #ffffff);
  --button: var(--color-botones, #2563eb);
  --button-text: var(--color-texto-botones, #ffffff);
  --line: color-mix(in srgb, var(--text) 10%, transparent);
  --muted: color-mix(in srgb, var(--text) 52%, transparent);
  --surface: color-mix(in srgb, var(--card) 88%, black);

  position: fixed;
  inset: 0;
  z-index: 10000;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 18px;
  background: rgba(0, 0, 0, 0.82);
  font-family: 'Inter', sans-serif;
}

.modal-shell {
  width: 100%;
  max-width: 465px;
  max-height: 94vh;
  display: flex;
  flex-direction: column;
  overflow: hidden;
  border: 1px solid var(--line);
  border-radius: 17px;
  background: var(--card);
  box-shadow: 0 28px 75px rgba(0, 0, 0, 0.6);
}

/* =========================================================
   MODAL HEADER
========================================================= */

.modal-header {
  flex-shrink: 0;
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 15px;
  padding: 15px 17px;
  border-bottom: 1px solid var(--line);
}

.header-left {
  min-width: 0;
  display: flex;
  align-items: center;
  gap: 10px;
}

.header-icon {
  width: 36px;
  height: 36px;
  flex-shrink: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  border: 1px solid
    color-mix(in srgb, var(--accent) 25%, transparent);
  border-radius: 9px;
  color: #93c5fd;
  background:
    color-mix(in srgb, var(--accent) 8%, transparent);
}

.modal-kicker {
  display: block;
  margin-bottom: 1px;
  color: var(--accent);
  font-size: 0.49rem;
  font-weight: 800;
  letter-spacing: 1px;
}

.modal-header h3 {
  margin: 0;
  color: var(--title);
  font-family: 'Oswald', sans-serif;
  font-size: 0.96rem;
  font-weight: 600;
  letter-spacing: 0.3px;
}

.modal-header p {
  margin: 1px 0 0;
  color: var(--muted);
  font-size: 0.58rem;
}

.close-button {
  width: 31px;
  height: 31px;
  flex-shrink: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  border: 1px solid var(--line);
  border-radius: 8px;
  background: var(--surface);
  color: var(--muted);
  cursor: pointer;
  transition:
    background 0.17s ease,
    border-color 0.17s ease,
    color 0.17s ease;
}

.close-button:hover:not(:disabled) {
  border-color:
    color-mix(in srgb, var(--text) 20%, transparent);
  background:
    color-mix(in srgb, var(--text) 7%, var(--surface));
  color: var(--text);
}

.close-button:disabled {
  cursor: not-allowed;
  opacity: 0.45;
}

/* =========================================================
   VIEWPORT
========================================================= */

.receipt-viewport {
  min-height: 0;
  flex: 1;
  overflow-y: auto;
  padding: 18px;
  background: #090a0c;
  scrollbar-width: thin;
  scrollbar-color: #34363d transparent;
}

.receipt-viewport::-webkit-scrollbar {
  width: 5px;
}

.receipt-viewport::-webkit-scrollbar-track {
  background: transparent;
}

.receipt-viewport::-webkit-scrollbar-thumb {
  border-radius: 10px;
  background: #34363d;
}

/* =========================================================
   RECEIPT
========================================================= */

.receipt {
  width: 100%;
  max-width: 350px;
  margin: 0 auto;
  overflow: hidden;
  border-radius: 5px;
  background: #ffffff;
  color: #18181b;
  box-shadow: 0 13px 32px rgba(0, 0, 0, 0.35);
}

/* =========================================================
   RECEIPT HEADER
========================================================= */

.receipt-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 15px;
  padding: 20px 19px 17px;
  border-top: 5px solid #2563eb;
  border-bottom: 1px solid #e4e4e7;
}

.receipt-brand {
  min-width: 0;
  display: flex;
  align-items: center;
  gap: 9px;
}

.brand-mark {
  width: 37px;
  height: 37px;
  flex-shrink: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 9px;
  background: #2563eb;
  color: #ffffff;
}

.brand-mark span {
  font-family: 'Oswald', sans-serif;
  font-size: 1.3rem;
  font-weight: 700;
}

.brand-copy strong {
  display: block;
  color: #111827;
  font-family: 'Oswald', sans-serif;
  font-size: 0.91rem;
  line-height: 1;
  letter-spacing: 0.4px;
}

.brand-copy span {
  display: block;
  margin-top: 3px;
  color: #6b7280;
  font-family: 'Inter', sans-serif;
  font-size: 0.46rem;
  font-weight: 700;
  letter-spacing: 1px;
}

.receipt-type {
  min-width: 0;
  text-align: right;
}

.receipt-type span {
  display: block;
  margin-bottom: 3px;
  color: #9ca3af;
  font-family: 'Inter', sans-serif;
  font-size: 0.48rem;
  font-weight: 700;
  letter-spacing: 0.5px;
}

.receipt-type strong {
  display: block;
  max-width: 130px;
  overflow: hidden;
  color: #111827;
  font-family: 'IBM Plex Mono', monospace;
  font-size: 0.59rem;
  text-overflow: ellipsis;
  white-space: nowrap;
}

/* =========================================================
   STATUS
========================================================= */

.receipt-status {
  display: grid;
  grid-template-columns: auto 1fr auto;
  align-items: center;
  gap: 9px;
  margin: 15px 19px;
  padding: 10px;
  border: 1px solid #bbf7d0;
  border-radius: 8px;
  background: #f0fdf4;
}

.status-icon {
  width: 30px;
  height: 30px;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 50%;
  background: #16a34a;
  color: #ffffff;
}

.status-copy strong {
  display: block;
  color: #166534;
  font-family: 'Inter', sans-serif;
  font-size: 0.62rem;
  font-weight: 800;
}

.status-copy span {
  display: block;
  margin-top: 1px;
  color: #4d7c5d;
  font-family: 'Inter', sans-serif;
  font-size: 0.47rem;
}

.status-code {
  text-align: right;
}

.status-code span {
  display: block;
  color: #6b7280;
  font-family: 'Inter', sans-serif;
  font-size: 0.43rem;
}

.status-code strong {
  display: block;
  margin-top: 1px;
  color: #16a34a;
  font-family: 'IBM Plex Mono', monospace;
  font-size: 0.63rem;
}

/* =========================================================
   META
========================================================= */

.receipt-meta {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  margin: 0 19px 15px;
  padding: 10px 0;
  border-top: 1px solid #e5e7eb;
  border-bottom: 1px solid #e5e7eb;
}

.receipt-meta > div {
  min-width: 0;
  padding: 0 8px;
  border-right: 1px solid #e5e7eb;
}

.receipt-meta > div:first-child {
  padding-left: 0;
}

.receipt-meta > div:last-child {
  padding-right: 0;
  border-right: 0;
}

.receipt-meta span {
  display: block;
  margin-bottom: 3px;
  color: #9ca3af;
  font-family: 'Inter', sans-serif;
  font-size: 0.43rem;
  font-weight: 700;
  letter-spacing: 0.4px;
  text-transform: uppercase;
}

.receipt-meta strong {
  display: block;
  overflow: hidden;
  color: #27272a;
  font-family: 'IBM Plex Mono', monospace;
  font-size: 0.55rem;
  font-weight: 600;
  text-overflow: ellipsis;
  white-space: nowrap;
}

/* =========================================================
   SECTIONS
========================================================= */

.receipt-section {
  padding: 0 19px 15px;
}

.section-label {
  margin-bottom: 9px;
  color: #2563eb;
  font-family: 'Inter', sans-serif;
  font-size: 0.46rem;
  font-weight: 800;
  letter-spacing: 0.8px;
}

.information-list {
  overflow: hidden;
  border: 1px solid #e5e7eb;
  border-radius: 7px;
}

.information-row {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: 15px;
  padding: 8px 10px;
  border-bottom: 1px solid #f0f1f3;
}

.information-row:last-child {
  border-bottom: 0;
}

.information-row span {
  flex-shrink: 0;
  color: #9ca3af;
  font-family: 'Inter', sans-serif;
  font-size: 0.49rem;
  font-weight: 600;
}

.information-row strong {
  max-width: 62%;
  color: #27272a;
  font-family: 'Inter', sans-serif;
  font-size: 0.54rem;
  font-weight: 700;
  text-align: right;
  word-break: break-word;
}

.information-row .mono {
  font-family: 'IBM Plex Mono', monospace;
}

/* =========================================================
   CONCEPT
========================================================= */

.concept-header {
  display: grid;
  grid-template-columns: 1fr auto;
  gap: 10px;
  padding: 0 2px 6px;
  border-bottom: 1px solid #d4d4d8;
  color: #9ca3af;
  font-family: 'Inter', sans-serif;
  font-size: 0.45rem;
  font-weight: 700;
}

.concept-row {
  display: grid;
  grid-template-columns: 1fr auto;
  align-items: center;
  gap: 10px;
  padding: 10px 2px;
  border-bottom: 1px solid #e5e7eb;
}

.concept-row > div {
  min-width: 0;
}

.concept-row > div strong {
  display: block;
  color: #18181b;
  font-family: 'Inter', sans-serif;
  font-size: 0.59rem;
}

.concept-row > div span {
  display: block;
  margin-top: 2px;
  color: #71717a;
  font-family: 'Inter', sans-serif;
  font-size: 0.49rem;
}

.concept-amount {
  color: #18181b;
  font-size: 0.63rem;
}

/* =========================================================
   TOTAL
========================================================= */

.totals-section {
  margin: 0 19px 16px;
  padding: 12px;
  border: 1px solid #dbeafe;
  border-radius: 8px;
  background: #f8fbff;
}

.subtotal-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 10px;
  margin-bottom: 6px;
}

.subtotal-row span {
  color: #71717a;
  font-family: 'Inter', sans-serif;
  font-size: 0.5rem;
}

.subtotal-row strong {
  color: #52525b;
  font-size: 0.54rem;
}

.total-divider {
  height: 1px;
  margin: 9px 0;
  background: #dbeafe;
}

.grand-total {
  display: flex;
  align-items: flex-end;
  justify-content: space-between;
  gap: 10px;
}

.grand-total > div span {
  display: block;
  color: #1d4ed8;
  font-family: 'Inter', sans-serif;
  font-size: 0.52rem;
  font-weight: 800;
}

.grand-total > div small {
  display: block;
  margin-top: 2px;
  color: #9ca3af;
  font-family: 'Inter', sans-serif;
  font-size: 0.43rem;
}

.grand-total > strong {
  color: #1d4ed8;
  font-size: 1.02rem;
  font-weight: 700;
}

/* =========================================================
   BARCODE
========================================================= */

.verification {
  margin: 0 19px 16px;
  padding: 13px 10px;
  border-top: 1px dashed #d4d4d8;
  border-bottom: 1px dashed #d4d4d8;
  text-align: center;
}

.barcode {
  height: 31px;
  display: flex;
  align-items: stretch;
  justify-content: center;
  gap: 1.2px;
  margin-bottom: 7px;
}

.barcode-line {
  width: 1px;
  display: block;
  background: #18181b;
}

.barcode-line.medium {
  width: 2px;
}

.barcode-line.wide {
  width: 3px;
}

.verification-number {
  display: block;
  color: #27272a;
  font-family: 'IBM Plex Mono', monospace;
  font-size: 0.61rem;
  letter-spacing: 2px;
}

.verification-label {
  display: block;
  margin-top: 3px;
  color: #a1a1aa;
  font-family: 'Inter', sans-serif;
  font-size: 0.42rem;
  font-weight: 700;
  letter-spacing: 0.5px;
}

/* =========================================================
   RECEIPT FOOTER
========================================================= */

.receipt-footer {
  padding: 0 19px 19px;
  text-align: center;
}

.footer-check {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  margin-bottom: 9px;
  padding: 4px 7px;
  border-radius: 5px;
  background: #f0fdf4;
  color: #16a34a;
  font-family: 'Inter', sans-serif;
  font-size: 0.43rem;
  font-weight: 800;
}

.receipt-footer p {
  margin: 0;
  color: #9ca3af;
  font-family: 'Inter', sans-serif;
  font-size: 0.48rem;
}

.receipt-footer > strong {
  display: block;
  margin-top: 3px;
  color: #52525b;
  font-family: 'Inter', sans-serif;
  font-size: 0.5rem;
}

.footer-divider {
  width: 35px;
  height: 2px;
  margin: 12px auto 8px;
  border-radius: 10px;
  background: #2563eb;
}

.receipt-footer > span {
  display: block;
  color: #52525b;
  font-family: 'Oswald', sans-serif;
  font-size: 0.54rem;
  font-weight: 700;
  letter-spacing: 0.5px;
}

.receipt-footer > small {
  display: block;
  margin-top: 2px;
  color: #a1a1aa;
  font-family: 'Inter', sans-serif;
  font-size: 0.4rem;
}

/* =========================================================
   MODAL FOOTER
========================================================= */

.modal-footer {
  flex-shrink: 0;
  padding: 12px 15px 14px;
  border-top: 1px solid var(--line);
  background: var(--card);
}

.download-title {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 10px;
  margin-bottom: 8px;
}

.download-title > span {
  color: var(--muted);
  font-size: 0.49rem;
  font-weight: 800;
  letter-spacing: 0.7px;
}

.download-title small {
  color: var(--muted);
  font-family: 'IBM Plex Mono', monospace;
  font-size: 0.46rem;
}

.modal-actions {
  display: grid;
  grid-template-columns: 1fr 1fr auto;
  gap: 7px;
}

.action-button {
  min-width: 0;
  min-height: 45px;
  display: flex;
  align-items: center;
  gap: 7px;
  padding: 6px 9px;
  border: 1px solid var(--line);
  border-radius: 9px;
  font-family: inherit;
  cursor: pointer;
  transition:
    border-color 0.17s ease,
    background 0.17s ease,
    transform 0.17s ease;
}

.action-button:hover:not(:disabled) {
  transform: translateY(-1px);
}

.action-button:disabled,
.close-footer-button:disabled {
  cursor: not-allowed;
  opacity: 0.5;
}

.action-icon {
  width: 28px;
  height: 28px;
  flex-shrink: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 7px;
}

.action-button > span:last-child {
  min-width: 0;
  text-align: left;
}

.action-button strong {
  display: block;
  font-size: 0.56rem;
}

.action-button small {
  display: block;
  margin-top: 1px;
  font-size: 0.43rem;
  opacity: 0.65;
}

.png-button {
  border-color:
    color-mix(in srgb, #3b82f6 28%, transparent);
  background: rgba(59, 130, 246, 0.06);
  color: #93c5fd;
}

.png-button:hover:not(:disabled) {
  border-color: #3b82f6;
  background: rgba(59, 130, 246, 0.1);
}

.png-button .action-icon {
  background: rgba(59, 130, 246, 0.1);
}

.pdf-button {
  border-color:
    color-mix(in srgb, #ef4444 25%, transparent);
  background: rgba(239, 68, 68, 0.05);
  color: #fca5a5;
}

.pdf-button:hover:not(:disabled) {
  border-color: #ef4444;
  background: rgba(239, 68, 68, 0.09);
}

.pdf-button .action-icon {
  background: rgba(239, 68, 68, 0.09);
}

.close-footer-button {
  min-width: 70px;
  padding: 0 11px;
  border: 1px solid var(--line);
  border-radius: 9px;
  background: var(--surface);
  color: var(--muted);
  font-family: inherit;
  font-size: 0.56rem;
  font-weight: 700;
  cursor: pointer;
  transition:
    border-color 0.17s ease,
    background 0.17s ease,
    color 0.17s ease;
}

.close-footer-button:hover:not(:disabled) {
  border-color:
    color-mix(in srgb, var(--text) 20%, transparent);
  color: var(--text);
}

/* =========================================================
   RESPONSIVE
========================================================= */

@media (max-width: 520px) {
  .modal-overlay {
    padding: 7px;
  }

  .modal-shell {
    max-height: 97vh;
    border-radius: 14px;
  }

  .modal-header {
    padding: 12px;
  }

  .receipt-viewport {
    padding: 12px 8px;
  }

  .modal-footer {
    padding: 10px;
  }

  .modal-actions {
    grid-template-columns: 1fr 1fr;
  }

  .close-footer-button {
    grid-column: 1 / -1;
    min-height: 38px;
  }
}

@media (max-width: 380px) {
  .receipt-header {
    padding: 16px 14px 14px;
  }

  .brand-mark {
    width: 32px;
    height: 32px;
  }

  .receipt-status,
  .receipt-meta,
  .totals-section,
  .verification {
    margin-left: 14px;
    margin-right: 14px;
  }

  .receipt-section,
  .receipt-footer {
    padding-left: 14px;
    padding-right: 14px;
  }

  .receipt-meta {
    grid-template-columns: 1fr 1fr;
    row-gap: 8px;
  }

  .receipt-meta > div:nth-child(2) {
    border-right: 0;
  }

  .receipt-meta > div:last-child {
    grid-column: 1 / -1;
    padding: 8px 0 0;
    border-top: 1px solid #e5e7eb;
  }

  .modal-actions {
    grid-template-columns: 1fr;
  }

  .close-footer-button {
    grid-column: auto;
  }
}

@media (prefers-reduced-motion: reduce) {
  .close-button,
  .action-button,
  .close-footer-button {
    transition: none !important;
  }
}
</style>